Car-sharing/CarSharingApp.Web/Controllers/DashboardController.cs
using CarSharingApp.Application.Contracts.Account;
using CarSharingApp.Application.Contracts.Vehicle;
using CarSharingApp.Web.Models;
using CarSharingApp.Web.Clients.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using Microsoft.AspNetCore.Authorization;

namespace CarSharingApp.Web.Controllers
{
    [Authorize]
    [Route("dashboard")]
    public sealed class DashboardController : Controller
    {
        private readonly IAccountServicePublicApiClient _accountServiceClient;
        private readonly IVehicleServicePublicApiClient _vehicleServiceClient;
        private readonly IRentalServicePublicApiClient _rentalServiceClient;
        private readonly IAzureBlobStoragePublicApiClient _blobStorageClient;

        public DashboardController(IAccountServicePublicApiClient accountServiceClient, 
                                   IVehicleServicePublicApiClient vehicleServiceClient,
                                   IRentalServicePublicApiClient rentalServiceClient,
                                   IAzureBlobStoragePublicApiClient blobStorageClient)
        {
            _accountServiceClient = accountServiceClient;
            _vehicleServiceClient = vehicleServiceClient;
            _rentalServiceClient = rentalServiceClient;
            _blobStorageClient = blobStorageClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _accountServiceClient.GetCustomerAccountData();

            switch (response.StatusCode)
            {
                case HttpStatusCode.Unauthorized:
                    return RedirectToAction("Unauthorized401Error", "CustomExceptionHandle");
                default:
                    break;
            }

            response.EnsureSuccessStatusCode();

            AccountDataResponse responseModel = await response.Content.ReadFromJsonAsync<AccountDataResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            return View(responseModel);
        }

        #region Partial views rendering

        [HttpGet]
        [Route("rentalsPartial")]
        public async Task<IActionResult> RentalsArticlePartial([FromQuery] string searchBy, 
                                                               [FromQuery] string searchInput, 
                                                               [FromQuery] int page = 1, 
                                                               [FromQuery] int pageSize = 3)
        {
            var response = await _accountServiceClient.GetCustomerRentalsAccountRepresentation();

            response.EnsureSuccessStatusCode();

            AccountRentalsDataResponse responseModel = await response.Content.ReadFromJsonAsync<AccountRentalsDataResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            ViewBag.SearchBy = searchBy;
            ViewBag.SearchRentalInput = searchInput;

            if (page < 1)
                page = 1;

            if (searchBy == "Amount" && searchInput != null)
            {
                var partialViewModel = responseModel.Rentals.Where(r => r.Amount.StartsWith(searchInput)).ToList();

                Pager pager = new Pager(partialViewModel.Count(), page, pageSize);
                int rentalsSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.RentalsCount = partialViewModel.Count();

                return PartialView("_RentalsArticle", partialViewModel.Skip(rentalsSkip).Take(pager.PageSize).ToList());
            }
            else if (searchBy == "VehicleName" && searchInput != null)
            {
                var partialViewModel = responseModel.Rentals.Where(r => r.VehicleName.StartsWith(searchInput)).ToList();

                Pager pager = new Pager(partialViewModel.Count(), page, pageSize);
                int rentalsSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.RentalsCount = partialViewModel.Count();

                return PartialView("_RentalsArticle", partialViewModel.Skip(rentalsSkip).Take(pager.PageSize).ToList());
            }
            else
            {
                Pager pager = new Pager(responseModel.Rentals.Count(), page, pageSize);
                int rentalsSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.RentalsCount = responseModel.Rentals.Count();

                return PartialView("_RentalsArticle", responseModel.Rentals.Skip(rentalsSkip).Take(pager.PageSize).ToList());
            }
        }

        [HttpGet]
        [Route("vehiclesPartial")]
        public async Task<IActionResult> VehiclesArticlePartial([FromQuery] string searchBy, 
                                                                [FromQuery] string searchInput, 
                                                                [FromQuery] int page = 1, 
                                                                [FromQuery] int pageSize = 3)
        {
            var response = await _accountServiceClient.GetCustomerVehiclesAccountRepresentation();

            response.EnsureSuccessStatusCode();

            AccountVehiclesDataResponse responseModel = await response.Content.ReadFromJsonAsync<AccountVehiclesDataResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            ViewBag.SearchBy = searchBy;
            ViewBag.SearchInput = searchInput;

            if (page < 1)
                page = 1;

            if (searchBy == "Price" && searchInput != null)
            {
                var partialViewModel = responseModel.Vehicles.Where(v => v.HourlyPrice.StartsWith(searchInput) || v.DailyPrice.StartsWith(searchInput)).ToList();

                Pager pager = new Pager(partialViewModel.Count(), page, pageSize);
                int vehiclesSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.VehiclesCount = partialViewModel.Count();

                return PartialView("_VehiclesArticle", partialViewModel.Skip(vehiclesSkip).Take(pager.PageSize).ToList());
            } else if (searchBy == "Name" && searchInput != null)
            {
                var partialViewModel = responseModel.Vehicles.Where(v => v.Name.StartsWith(searchInput)).ToList();

                Pager pager = new Pager(partialViewModel.Count(), page, pageSize);
                int vehiclesSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.VehiclesCount = partialViewModel.Count();

                return PartialView("_VehiclesArticle", partialViewModel.Skip(vehiclesSkip).Take(pager.PageSize).ToList());
            }
            else
            {
                Pager pager = new Pager(responseModel.Vehicles.Count(), page, pageSize);
                int vehiclesSkip = (page - 1) * pageSize;
                ViewBag.Pager = pager;
                ViewBag.VehiclesCount = responseModel.Vehicles.Count();

                return PartialView("_VehiclesArticle", responseModel.Vehicles.Skip(vehiclesSkip).Take(pager.PageSize).ToList());
            }
        }

        [HttpGet]
        [Route("notesPartial")]
        public async Task<IActionResult> NotesArticlePartial([FromQuery] string type)
        {
            var response = await _accountServiceClient.GetActionNotesOfTheSpecificType(type);

            response.EnsureSuccessStatusCode();

            AccountActionNotesResponse responseModel = await response.Content.ReadFromJsonAsync<AccountActionNotesResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            return PartialView("_NotesArticle", responseModel);
        }

        [HttpGet]
        [Route("statisticsPartial")]
        public async Task<IActionResult> StatisticsArticlePartial()
        {
            var response = await _accountServiceClient.GetCustomerAccountStatistics();

            response.EnsureSuccessStatusCode();

            AccountStatisticsDataResponse responseModel = await response.Content.ReadFromJsonAsync<AccountStatisticsDataResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            return PartialView("_StatisticsArticle", responseModel);
        }

        #endregion

        #region Partial views actions

        [HttpGet]
        [Route("deleteAndRenderPartial/vehicle")]
        public async Task<IActionResult> DeleteVehicleAndRenderVehiclesArticlePartial([FromQuery] string vehicleId, 
                                                                                      [FromQuery] string vehicleImage, 
                                                                                      [FromQuery] string searchBy, 
                                                                                      [FromQuery] string searchInput)
        {
            var response = await _vehicleServiceClient.DeleteVehicle(vehicleId);
            response.EnsureSuccessStatusCode();

            await _blobStorageClient.DeleteBlobAsync(vehicleImage);

            return Redirect($"/dashboard/vehiclesPartial?searchBy={searchBy}&searchInput={searchInput}");
        }

        [HttpGet]
        [Route("updateAndRenderPartial/vehicle/status")]
        public async Task<IActionResult> UpdateVehicleStatus([FromQuery] string vehicleId,
                                                             [FromQuery] string isConfirmedByAdmin, 
                                                             [FromQuery] string isPublished, 
                                                             [FromQuery] string isOrdered,
                                                             [FromQuery] string searchBy, 
                                                             [FromQuery] string searchInput)
        {
            var requestModel = new UpdateVehicleStatusRequest(
                bool.Parse(isOrdered),

Car-sharing/CarSharingApp.Web/Controllers/EditCustomerDataController.cs
using CarSharingApp.Application.Contracts.Customer;
using CarSharingApp.Web.Clients.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarSharingApp.Controllers
{
    [Authorize]
    [Route("customer/current/edit")]
    public sealed class EditCustomerDataController : Controller
    {
        private readonly ICustomerServicePublicApiClient _customerServiceClient;

        public EditCustomerDataController(ICustomerServicePublicApiClient customerServiceClient)
        {
            _customerServiceClient = customerServiceClient;
        }

        [HttpGet]
        [Route("information")]
        public async Task<IActionResult> Index()
        {
            var response = await _customerServiceClient.GetCustomerInformation();

            response.EnsureSuccessStatusCode();

            CustomerDataResponse responseModel = await response.Content.ReadFromJsonAsync<CustomerDataResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            return View(responseModel);
        }

        [HttpPost]
        [Route("information")]
        public async Task<IActionResult> Edit([FromForm] CustomerDataResponse request)
        {
            if (!ModelState.IsValid)
                return View("Index", request);

            var response = await _customerServiceClient.EditCustomerInformation(
                MapUpdateCustomerInfoRequest(request));

            HttpContext.Session.SetString("CustomerImage", request.Image);
            HttpContext.Session.SetString("ChangedAccountData", "true");

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("password")]
        public async Task<IActionResult> ChangePassword([FromForm] string newPassword)
        {
            var response = await _customerServiceClient.EditCustomerPassword(
                MapUpdateCustomerPasswordRequest(newPassword));

            string url = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host.Value}" + Url.Action("Index", "Dashboard")
                ?? throw new NullReferenceException(nameof(url));

            Response.Headers.Add("Location", url);
            return Redirect(url);
        }

        private UpdateCustomerInfoRequest MapUpdateCustomerInfoRequest(CustomerDataResponse response)
        {
            return new UpdateCustomerInfoRequest(
                response.FirstName,
                response.LastName,
                response.PhoneNumber,
                response.DriverLicenseIdentifier,
                response.HasAcceptedNewsSharing,
                response.ProfileDescription,
                response.Image);
        }

        private UpdateCustomerPasswordRequest MapUpdateCustomerPasswordRequest(string newPassword)
        {
            return new UpdateCustomerPasswordRequest(
                currentPassword: string.Empty,
                newPassword: newPassword);
        }
    }
}

Car-sharing/CarSharingApp.Web/Views/Dashboard/Index.cshtml
@inject IConfiguration _configuration;
@model CarSharingApp.Application.Contracts.Account.AccountDataResponse;

<main>
    <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
        <div class="container-xl px-4">
            <div class="page-header-content pt-4">
                <div class="row align-items-center justify-content-between">
                    <div class="d-flex justify-content-between align-items-center card col-lg-12 p-3 mt-4">
                        <div class="col-lg-5 d-flex justify-content-center">
                            <img class="rounded-circle" src="@(string.Join("", _configuration["AzureBlobStorage:CustomersAccountImagesPath"], Model.Customer.Image))" width="170" height="170">
                        </div>
                        <div class="col-lg-7 d-flex flex-column">
                            <label class="text-center" style="font-size: 30px;">@string.Join(" ", Model.Customer.FirstName, Model.Customer.LastName)</label>
                            <label class="text-center" style="font-size: 15px;">@Model.Customer.Description</label>
                            <label class="text-center mt-2" style="font-size: 15px;">@Model.Customer.Email</label>
                            <label class="text-center" style="font-size: 15px;">@($"{Model.Customer.Country}, {Model.Customer.City}, {Model.Customer.StreetAddress} {Model.Customer.AptSuiteEtc}")</label>
                            <label class="text-center" style="font-size: 15px;">@Model.Customer.PhoneNumber</label>
                            <a class="btn btn-sm btn-outline-secondary mt-3 text-center ms-auto me-auto" asp-controller="EditCustomerData" asp-action="Index" style="width: 200px;" data-toggle="collapse">
                                Edit account info
                                <i class="fa-solid fa-square-pen ms-2"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-auto mt-4">
                        <div class="page-header-title d-flex h1">
                            <div class="page-header-icon me-3">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline>
                                </svg>
                            </div>
                            Dashboard
                        </div>
                        <div class="page-header-subtitle">You can check account overview and activity summary below</div>
                    </div>
                    <div class="col-12 col-xl-auto mt-4">
                        <div class="input-group input-group-joined border-0" style="width: 14rem">
                            <span class="input-group-text">
                                <i class="fa-regular fa-clock"></i>
                            </span>
                            <span class="form-control d-flex justify-content-center" id="currentTimeInput"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main page content-->
    <div class="container-xl px-4 mt-4">
        <div class="row">
            <div class="col-xxl-4 col-xl-12 mb-4">
                <div class="card h-100">
                    <div class="card-body h-100 p-5">
                        <div class="row align-items-center">
                            <div class="col-xl-8 col-xxl-12">
                                <div class="text-center text-xl-start text-xxl-center mb-4 mb-xl-0 mb-xxl-4">
                                    <h1 class="text-primary">@($"Welcome back {Model.Customer.Username}!")</h1>
                                    <p class="text-gray-700 mb-0">Thank you for being with us. We value every customer who makes the world a better place by helping others, lending and paying for other people's vehicles. Watch, learn and explore new horizons with Sam Solutions Vehicles Sharing Service!</p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-xxl-12 d-flex justify-content-center">
                                <img class="img-fluid" style="width: 260px;" src="~/Images/AccountDashboardPage/girl.png">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xxl-4 col-xl-6 mb-4">
                <div class="card card-header-actions h-100">
                    <div class="card-header d-flex align-items-center text-primary">
                        Recent Activity
                        <div class="dropdown ms-2">
                            <button class="btn btn-transparent-dark btn-icon dropdown-toggle" id="dropdownMenuButton" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="img-fluid" style="width: 24px;" src="~/Images/AccountDashboardPage/menu.png">
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                <h6 class="dropdown-header">Filter Activity:</h6>
                                <a id="showAllNotesBtn" class="dropdown-item" href="#!"><i class="fa-solid fa-globe me-2"></i><span>All</span></a>
                                <a id="showAccountNotesBtn" class="dropdown-item" href="#!"><i class="fa-regular fa-user me-2"></i><span>Account</span></a>
                                <a id="showVehiclesNotesBtn" class="dropdown-item" href="#!"><i class="fa-solid fa-car-rear me-2"></i><span>Vehicles</span></a>
                                <a id="showOrdersNotesBtn" class="dropdown-item" href="#!"><i class="fa-regular fa-credit-card me-2"></i><span>Orders</span></a>
                            </div>
                        </div>
                    </div>

                    <div id="notesPartialZone">

                    </div>
                </div>
            </div>

            <div class="col-xxl-4 col-xl-6 mb-4">
                <div class="card card-header-actions h-100">
                    <div class="card-header d-flex align-items-center text-primary">
                        Statistics Tracker
                    </div>
                    <div id="statisticsPartialZone">

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card border-primary shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Earnings (Monthly)</div>
                                <div class="text-lg fw-bold">$40,000</div>
                            </div>
                            <i class="fa-solid fa-calendar-days fa-2x"></i>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between small">
                        <a class="stretched-link link-secondary nav-link" href="#!">View Report</a>
                        <div>
                            <i class="fas fa-angle-right"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card border-warning shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Earnings (Annual)</div>
                                <div class="text-lg fw-bold">$215,000</div>
                            </div>
                            <i class="fa-solid fa-dollar-sign fa-2x"></i>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between small">
                        <a class="stretched-link link-secondary nav-link" href="#!">View Report</a>
                        <div>
                            <i class="fas fa-angle-right"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card border-success shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Vehicles Rented</div>
                                <div class="text-lg fw-bold">@Model.Customer.VehiclesRented</div>
                            </div>
                            <i class="fa-regular fa-square-check fa-2x"></i>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between small">
                        <a class="stretched-link link-secondary nav-link" href="#!">View Tasks</a>
                        <div>
                            <i class="fas fa-angle-right"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-3 mb-4">
                <div class="card border-danger shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="me-3">
                                <div class="text-white-75 small">Vehicles Shared</div>
                                <div class="text-lg fw-bold">@Model.Customer.VehiclesShared</div>
                            </div>
                            <i class="fa-regular fa-comment fa-2x"></i>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between small">
                        <a class="stretched-link link-secondary nav-link" href="#!">View Requests</a>
                        <div>
                            <i class="fas fa-angle-right"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header text-primary">Vehicles Management</div>
            <div id="vehiclesPartialZone">

            </div>
        </div>

        <div class="card mb-5">
            <div class="card-header text-primary">Rentals Management</div>
            <div id="rentalsPartialZone">
            </div>
        </div>

    </div>
</main>


<script>
    $('#notesPartialZone').load("/dashboard/notesPartial?type=All");
    $('#statisticsPartialZone').load("/dashboard/statisticsPartial");
    $('#vehiclesPartialZone').load("/dashboard/vehiclesPartial");
    $('#rentalsPartialZone').load("/dashboard/rentalsPartial");

    $(function(){
        $('#showAllNotesBtn').click(function(){
            $('#notesPartialZone').load("/dashboard/notesPartial?type=All");
        })
    });
    $(function () {
        $('#showAccountNotesBtn').click(function () {
            $('#notesPartialZone').load("/dashboard/notesPartial?type=Account");
        })
    });
    $(function(){
        $('#showVehiclesNotesBtn').click(function () {
            $('#notesPartialZone').load("/dashboard/notesPartial?type=Vehicles");
        })
    });
    $(function(){
        $('#showOrdersNotesBtn').click(function(){
            $('#notesPartialZone').load("/dashboard/notesPartial?type=Orders");
        })
    });
</script>

<!--Refresh time script goes here-->
<script>
    const timeDisplay = document.getElementById("currentTimeInput");
    function refreshTime() {
        const dateString = new Date().toLocaleString();
        const formattedString = dateString.replace(", ", " - ");
        timeDisplay.textContent = formattedString;
    }
    setInterval(refreshTime, 1000);
</script>

Car-sharing/CarSharingApp.Web/Views/Dashboard/_NotesArticle.cshtml
@model CarSharingApp.Application.Contracts.Account.AccountActionNotesResponse;

<div class="container py-2">

    @foreach (var note in Model.ActionNotes)
    {
        if (CarSharingApp.Domain.SmartEnums.NoteType.FromName(note.Type) == CarSharingApp.Domain.SmartEnums.NoteType.AddedNewVehicle)
        {
            <div class="row">
                <div class="col py-2">
                    <div class="card border-success shadow">
                        <div class="card-body">
                            <div class="float-right text-success">@(TimeZoneInfo.ConvertTimeFromUtc(note.ActionMadeTime, TimeZoneInfo.Local).ToString("ddd MMM dd yyy h:mm tt", System.Globalization.CultureInfo.InvariantCulture))</div>
                            <h4 class="card-title text-success">@note.Type</h4>
                            <p class="card-text">@note.Note</p>
                            <button class="btn btn-sm btn-outline-secondary" type="button" data-target="#t2_details" data-toggle="collapse" onclick="TryRedirect('@note.ActionEntityId.ToString()')">Show Details ▼</button>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col py-2">
                    <div class="card">
                        <div class="card-body">
                            <div class="float-right text-muted">@(TimeZoneInfo.ConvertTimeFromUtc(note.ActionMadeTime, TimeZoneInfo.Local).ToString("ddd MMM dd yyy h:mm tt", System.Globalization.CultureInfo.InvariantCulture))</div>
                            <h4 class="card-title text-muted">@note.Type</h4>
                            <p class="card-text">@note.Note</p>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

<script>
    function TryRedirect(id){
        $.ajax({
            type: 'GET',
            url: 'dashboard/checkAvailability/vehicle',
            contentType: "application/json; charset=utf-8",
            data: {id: id},
            cache: false,
            async: true,
            success: function(data) {
                if (data) {
                    window.location.href = "/vehicle/information?vehicleId=" + id
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                ShowErrorMessage("Vehicle does not exist any more.");
            }
        });
    }
</script>

Car-sharing/CarSharingApp.Web/Views/Dashboard/_StatisticsArticle.cshtml
@model CarSharingApp.Application.Contracts.Account.AccountStatisticsDataResponse;

<div class="card-body">
    <h4 class="small">
        Rented vehicles
        <span class="float-end fw-bold">@(Model.VehiclesRentedToTheirTotalNumber)%</span>
    </h4>
    <div class="progress mb-4"><div class="progress-bar bg-info" role="progressbar" style="width: @(Model.VehiclesRentedToTheirTotalNumber)%" aria-valuenow="@(Model.VehiclesRentedToTheirTotalNumber)" aria-valuemin="0" aria-valuemax="100"></div></div>
    <p class="card-text">The number of your currently rented vehicles to their total number</p>
    <h4 class="small">
        Published vehicles
        <span class="float-end fw-bold">@(Model.VehiclesPublishedToTheirTotalNumber)%</span>
    </h4>
    <div class="progress mb-4"><div class="progress-bar bg-success" role="progressbar" style="width: @(Model.VehiclesPublishedToTheirTotalNumber)%" aria-valuenow="@(Model.VehiclesPublishedToTheirTotalNumber)" aria-valuemin="0" aria-valuemax="100"></div></div>
    <p class="card-text">The number of your currently listed vehicles in the catalog to their total number.</p>
    <h4 class="small">
        Hidden vehicles
        <span class="float-end fw-bold">@(Model.VehiclesHiddenToTheirTotalNumber)%</span>
    </h4>
    <div class="progress mb-4"><div class="progress-bar bg-warning" role="progressbar" style="width: @(Model.VehiclesHiddenToTheirTotalNumber)%" aria-valuenow="@(Model.VehiclesHiddenToTheirTotalNumber)" aria-valuemin="0" aria-valuemax="100"></div></div>
    <p class="card-text">The number of your currently hidden vehicles from the catalog to their total number.</p>
    <h4 class="small">
        Rented to Shared (or vice versa)
        <span class="float-end fw-bold">@(Model.RentedVehiclesToShared)%</span>
    </h4>
    <div class="progress mb-4"><div class="progress-bar" role="progressbar" style="width: @(Model.RentedVehiclesToShared)%" aria-valuenow="@(Model.RentedVehiclesToShared)" aria-valuemin="0" aria-valuemax="100"></div></div>
    <p class="card-text">The total number of your rented vehicles for all time to the total number of your orders. (or vice versa, depends on whichever is greater)</p>
</div>