Car-sharing/CarSharingApp.Web/Controllers/CatalogController.cs
using CarSharingApp.Application.Contracts.Vehicle;
using CarSharingApp.Web.Clients.Interfaces;
using CarSharingApp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarSharingApp.Controllers
{
    [AllowAnonymous]
    [Route("catalog")]
    public sealed class CatalogController : Controller
    {
        private readonly IVehicleServicePublicApiClient _vehicleServiceClient;

        public CatalogController(IVehicleServicePublicApiClient vehicleServiceClient)
        {
            _vehicleServiceClient = vehicleServiceClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region Partial views rendering

        [HttpGet]
        [Route("vehiclesPartial")]
        public async Task<IActionResult> VehiclesCatalogPartial([FromQuery] string searchBy, 
                                                                [FromQuery] string searchInput, 
                                                                [FromQuery] int page = 1, 
                                                                [FromQuery] int pageSize = 9)
        {
            var response = await _vehicleServiceClient.GetAllApprovedAndPublishedVehiclesCatalogRepresentation();
            var viewModel = await RenderCatalog(searchBy, searchInput, page, pageSize, response);

            return PartialView("_VehiclesCatalog", viewModel);
        }

        [HttpGet]
        [Route("advancedFilterPartial")]
        public IActionResult FilterModalPartial()
        {
            return PartialView("_FilterModal");
        }

        #endregion

        #region Partial views actions

        [HttpGet]
        [Route("search")]
        public async Task<IActionResult> AdvancedSearch([FromQuery] GetVehiclesByCriteriaRequest request, 
                                                        [FromQuery] string searchBy, 
                                                        [FromQuery] string searchInput, 
                                                        [FromQuery] int page = 1, 
                                                        [FromQuery] int pageSize = 9)
        {
            var response = await _vehicleServiceClient.GetAllApprovedAndPublishedVehiclesWithFilterCatalogRepresentation(request);
            var viewModel = await RenderCatalog(searchBy, searchInput, page, pageSize, response);

            return PartialView("_VehiclesCatalog", viewModel);
        }

        #endregion

        #region Helper methods

        [NonAction]
        private async Task<List<VehicleDisplayInCatalog>> RenderCatalog(string searchBy, string searchInput, int page, int pageSize, HttpResponseMessage response)
        {
            response.EnsureSuccessStatusCode();

            VehiclesDisplayInCatalogResponse responseModel = await response.Content.ReadFromJsonAsync<VehiclesDisplayInCatalogResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            ViewBag.SearchBy = searchBy;
            ViewBag.SearchInput = searchInput;

            if (page < 1)
                page = 1;

            List<VehicleDisplayInCatalog> partialViewModel;

            if (searchInput != null)
                partialViewModel = GetViewModel(responseModel, searchBy, searchInput);
            else
                partialViewModel = responseModel.Vehicles;

            Pager pager = new(partialViewModel.Count, page, pageSize);
            int vehiclesSkip = (page - 1) * pageSize;
            ViewBag.Pager = pager;
            ViewBag.VehiclesCount = partialViewModel.Count;

            return partialViewModel.Skip(vehiclesSkip).Take(pager.PageSize).ToList();
        }

        [NonAction]
        private List<VehicleDisplayInCatalog> GetViewModel(VehiclesDisplayInCatalogResponse serverResponse, string searchCriteria, string searchInput)
        {
            switch (searchCriteria)
            {
                case "Price":
                    return serverResponse.Vehicles.Where(v => v.HourlyRentalPrice.StartsWith(searchInput) || v.DailyRentalPrice.StartsWith(searchInput)).ToList();
                case "Name":
                    return serverResponse.Vehicles.Where(v => v.Name.StartsWith(searchInput)).ToList();
                case "BriefDescription":
                    return serverResponse.Vehicles.Where(v => v.BriefDescription.Contains(searchInput)).ToList();
                default:
                    return new List<VehicleDisplayInCatalog>();
            }
        }

        #endregion
    }
}

Car-sharing/CarSharingApp.Web/Controllers/SearchNearbyVehiclesController.cs
using CarSharingApp.Application.Contracts.Vehicle;
using CarSharingApp.Web.Clients.Interfaces;
using CarSharingApp.Web.Helpers.Models;
using CarSharingApp.Web.Helpers;
using CarSharingApp.Web.Primitives;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarSharingApp.Web.Controllers
{
    [AllowAnonymous]
    [Route("nearbyVehicles")]
    public sealed class SearchNearbyVehiclesController : WebAppController
    {
        private readonly IVehicleServicePublicApiClient _vehicleServiceClient;

        public SearchNearbyVehiclesController(IVehicleServicePublicApiClient vehicleServiceClient)
        {
            _vehicleServiceClient = vehicleServiceClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region Partial views rendering 

        [HttpGet]
        [Route("mapPartial")]
        public async Task<IActionResult> RenderMapPartial()
        {
            var response = await _vehicleServiceClient.GetAllApprovedAndPublishedVehiclesMapRepresentation();

            if (!response.IsSuccessStatusCode)
            {
                MyControllerContext context = GenerateControllerContext();
                var errorResponseViewModel = MyCustomResponseAnalyzer.Analize(myControllerContext: context,
                                                                              response: response,
                                                                              onErrorStatusCode_ViewName: "_MapArticle",
                                                                              onErrorStatusCode_ViewModel: new List<VehicleDisplayOnMap>(),
                                                                              isReturningPartialView: true);

                return PartialView("_MapArticle", new List<VehicleDisplayOnMap>());
                //return errorResponseViewModel ?? throw new NullReferenceException(nameof(errorResponseViewModel));
            }

            VehiclesDisplayOnMapResponse responseModel = await response.Content.ReadFromJsonAsync<VehiclesDisplayOnMapResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            var viewModel = responseModel.Vehicles;

            return PartialView("_MapArticle", viewModel);
        }

        #endregion

        #region Partial views actions

        [HttpGet]
        [Route("getNearbyVehicles")]
        public async Task<JsonResult> GetNearbyVehicles([FromQuery] string latitude, 
                                                        [FromQuery] string longitude, 
                                                        [FromQuery] int vehiclesCount)
        {
            var requestModel = new GetNearbyVehiclesMapRepresentationRequest(latitude, longitude, vehiclesCount);

            var response = await _vehicleServiceClient.GetAllApprovedAndPublishedNearbyVehiclesMapRepresentation(requestModel);

            if (!response.IsSuccessStatusCode)
            {
                MyControllerContext context = GenerateControllerContext();
                var errorResponseViewModel = MyCustomResponseAnalyzer.Analize<object>(myControllerContext: context,
                                                                                      response: response,
                                                                                      onErrorStatusCode_ViewName: "",
                                                                                      onErrorStatusCode_ViewModel: null);

                return Json(new NearbyVehiclesDisplayOnMapResponse(new List<NearbyVehicleDisplayOnMapResponse>()));
            }

            NearbyVehiclesDisplayOnMapResponse responseModel = await response.Content.ReadFromJsonAsync<NearbyVehiclesDisplayOnMapResponse>()
                ?? throw new NullReferenceException(nameof(responseModel));

            return Json(responseModel);
        }

        #endregion
    }
}

Car-sharing/CarSharingApp.Web/Views/Catalog/Index.cshtml
<div id="catalogCarousel" class="carousel slide mt-5" data-bs-ride="carousel" style="max-width: 1024px; margin: auto;">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#catalogCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#catalogCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#catalogCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="~/Images/CatalogPage/slider_image1.png" class="d-block w-100" alt="">
        </div>
        <div class="carousel-item" data-bs-interval="10000">
            <img src="https://picsum.photos/1024/300?grayscale" class="d-block w-100" alt="">
        </div>
        <div class="carousel-item" data-bs-interval="10000">
            <img src="https://picsum.photos/1023/300?grayscale" class="d-block w-100" alt="">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#catalogCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#catalogCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<section class="mt-5 text-center container">
    <div class="row mt-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Explore SamSolutions Vehicles Prices for Daily and Hourly Rental</h1>
            <p class="lead text-muted">All vehicles are available for the rent and were provided by different people all over the world. Share your personal vehicles, rent them from other customers and feel all the charm and comfort of SamVehicles service.</p>
            <p>
                <button id="searchByCriteriaBtn" type="button" class="btn btn-primary my-2 me-1" data-bs-toggle="modal" data-bs-target="#searchByCriteriaModal">Search vehicles by criteria</button>

                <a asp-controller="SearchNearbyVehicles" asp-action="Index" class="btn btn-secondary my-2">Search nearby vehicles</a>
            </p>
        </div>
    </div>
</section>

<h1 class="fw-light d-flex justify-content-center mt-4">Choose vehicle that suits you</h1>

<div id="vehiclesPartialZone">

</div>

<div id="filterModalPartialZone">

</div>


<script src="~/js/catalogPage.js" asp-append-version="true"></script>

<script>
    $('#vehiclesPartialZone').load("/catalog/vehiclesPartial");
    $('#filterModalPartialZone').load("/catalog/advancedFilterPartial");
</script>

Car-sharing/CarSharingApp.Web/Views/Catalog/_VehiclesCatalog.cshtml
@inject IConfiguration _configuration;
@model List<CarSharingApp.Application.Contracts.Vehicle.VehicleDisplayInCatalog>;

@{
    CarSharingApp.Web.Models.Pager pager = new CarSharingApp.Web.Models.Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<fieldset id="vehiclesGroup">
    <div class="datatable-top d-flex align-items-center mt-4 mb-4">
        <div class="datatable-search d-flex align-items-center">
            <label class="ms-2 me-4 text-nowrap">Search by:</label>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptionsForVehicles" id="searchByNameRadio" value="option1" @(ViewBag.SearchBy == null || ViewBag.SearchBy == "Name" ? "checked" : "")>
                <label class="form-check-label text-nowrap" for="searchByNameRadio">Name</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptionsForVehicles" id="searchByBriefDescriptionRadio" value="option2" @(ViewBag.SearchBy == "BriefDescription" ? "checked" : "")>
                <label class="form-check-label text-nowrap" for="searchByBriefDescriptionRadio">Brief Description</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptionsForVehicles" id="searchByPriceRadio" value="option3" @(ViewBag.SearchBy == "Price" ? "checked" : "")>
                <label class="form-check-label text-nowrap" for="searchByPriceRadio">Price</label>
            </div>
            <input id="searchInput" name="searchInput" type="text" class="form-control ms-4" placeholder="Type here..." value="@ViewBag.SearchInput">
            <button id="searchButton" type="button" class="btn btn-outline-secondary ms-2" style="border-radius: 30px;">Search</button>
        </div>
    </div>
</fieldset>

<div class="row justify-content-center row-cols-1 row-cols-md-3 g-4 mb-4">
    @foreach(var vehicle in Model)
    {
        <div class="col">
            <div class="card h-100">
                <img src="@(_configuration["AzureBlobStorage:VehiclesImagesPath"] + vehicle.Image)" class="card-img-top">
                <div class="card-body">
                    <h3 class="card-title">@vehicle.Name</h3>
                    <p class="card-text">@vehicle.BriefDescription</p>
                    <h4 class="card-text">@vehicle.HourlyRentalPrice $<span class="text-muted h5">/hr - </span>@vehicle.DailyRentalPrice $<span class="text-muted h5">/day</span></h4>
                    <a href="@Url.Action("Index", "VehicleInformation", new {vehicleId = vehicle.VehicleId})" class="btn btn-info mt-2" style="width:max-content">Information</a>
                    <p></p>

                    @if (vehicle.TimesOrdered == 0)
                    {
                        <p class="card-text"><small class="text-muted">New vehicle!</small></p>
                    }
                    else
                    {
                        <p class="card-text"><small class="text-muted">Was rented @(vehicle.TimesOrdered) times.</small></p>
@*                        int timeDaysDifference = Convert.ToInt32((DateTime.Now - (DateTime)vehicle.LastTimeOrdered).TotalDays);
                        int timeHoursDifference = Convert.ToInt32((DateTime.Now - (DateTime)vehicle.LastTimeOrdered).TotalHours % 24);
                        int timeMinutesDifference = Convert.ToInt32((DateTime.Now - (DateTime)vehicle.LastTimeOrdered).TotalMinutes % 24 % 60) + 1;

                        <p class="card-text"><small class="text-muted">Last taken @(timeDaysDifference > 0 ? $"{timeDaysDifference} days " : "")@(timeHoursDifference > 0 ? $"{timeHoursDifference} hours " : "")@($"{timeMinutesDifference} mins") ago</small></p>*@
                    }
                </div>
            </div>
        </div>
    }
</div>

@if (Model.Count() > 0)
{
    <div class="datatable-bottom d-flex align-items-center mb-5">
        <div class="datatable-info">Showing @((pager.CurrentPage - 1) * pager.PageSize + 1) to @(Model.Count() >= pager.PageSize ? (pager.CurrentPage - 1) * pager.PageSize + pager.PageSize : (pager.CurrentPage - 1) * pager.PageSize + Model.Count()) of @(ViewBag.VehiclesCount) vehicles</div>
        <nav class="datatable-pagination mb-0 ms-auto">
            @if (pager.TotalPages > 0)
            {
                <ul class="pagination mb-0">

                    @if (pager.CurrentPage > 1)
                    {
                        <li class="page-item">
                            <a href="javascript:void(0);" class="page-link" onclick="ChangePage(1)">First</a>
                        </li>
                        <li class="page-item">
                            <a href="javascript:void(0);" class="page-link" onclick="ChangePage(@(pager.CurrentPage - 1))">Previous</a>
                        </li>
                    }

                    @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                    {
                        <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                            <a href="javascript:void(0);" class="page-link" onclick="ChangePage(@(pge))">@pge</a>
                        </li>
                    }

                    @if (pager.CurrentPage < pager.TotalPages)
                    {
                        <li class="page-item">
                            <a href="javascript:void(0);" class="page-link" onclick="ChangePage(@(pager.CurrentPage + 1))">Next</a>
                        </li>
                        <li class="page-item">
                            <a href="javascript:void(0);" class="page-link" onclick="ChangePage(@(pager.TotalPages))">Last</a>
                        </li>
                    }

                </ul>
            }
        </nav>
    </div>
}
else
{
    <div class="mb-5">
        <h2 class="fw-light text-center mt-5 mb-2">There is nothing we can offer you 😞</h2>
        <p class="lead text-muted mb-5 text-center">Try to find something else or come back later.</p>
    </div>
}

<script>
    // When user click search button on vehicles table
    $(function Search() {
        $('#searchButton').click(function () {
            var value = $("#searchInput").val();
            if (document.getElementById("searchByNameRadio").checked) {
                $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=Name&searchInput=" + value);
            } else if (document.getElementById("searchByPriceRadio").checked) {
                $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=Price&searchInput=" + value);
            } else if (document.getElementById("searchByBriefDescriptionRadio").checked) {
                $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=BriefDescription&searchInput=" + value);
            }
        })
    });

    // When user click next/prev page on vehicles table
    function ChangePage(pageNumber) {
        var value = $("#searchInput").val();
        if (document.getElementById("searchByNameRadio").checked) {
            $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=Name&searchInput=" + value + "&page=" + pageNumber);
        } else if (document.getElementById("searchByPriceRadio").checked) {
            $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=Price&searchInput=" + value + "&page=" + pageNumber);
        } else if (document.getElementById("searchByBriefDescriptionRadio").checked) {
            $('#vehiclesPartialZone').load("/catalog/vehiclesPartial?searchBy=BriefDescription&searchInput=" + value + "&page=" + pageNumber);
        }
    };
</script>